AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  CodeCommitSourceRepo:
    Type: String
    Default: ''

  CodeCommitSourceBranch:
    Type: String
    Default: ''

  CostTagKey:
    Type: String
    Default: "osl-billing"

  CostTagValue:
    Type: String
    Default: ''

Resources:

  ContainerPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::Region}-${CostTagValue}-container-pipeline-role
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service: 
              - cloudformation.amazonaws.com
              - codebuild.amazonaws.com
              - codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: !Sub ${AWS::Region}-${CostTagValue}-container-pipeline-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "codecommit:GitPull"
                Resource: !Sub 'arn:aws:codecommit:*:*:${CodeCommitSourceRepo}'

  ProfileContainerCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${CostTagValue}-profile-containers
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:5.0
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
      ServiceRole: !GetAtt ContainerPipelineRole.Arn
      Tags:
        - Key: !Sub ${CostTagKey}
          Value: !Sub ${CostTagValue}
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2

          env:
            git-credential-helper: yes
            shell: bash
            secrets-manager:
              DH_CREDS: "dockerhub/creds"

          phases:
            install:
              runtime-versions:
                python: 3.9
              commands:
              - pip3 install boto3 --upgrade
            build:
              commands:
              - export DOCKER_REGISTRY="${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CostTagValue}-container"
              - echo "Logging into ECR...";
                $(aws ecr get-login --no-include-email --region ${AWS::Region})
              - echo "Logging into Docker Hub user...";
                dh_username=$(echo $DH_CREDS | cut -f1 -d' ');
                echo $dh_creds | cut -f2 -d' ' > dh.pass;
                cat dh.pass | docker login -u $dh_username --password-stdin;
              - cd profiles;
                for p in $(ls -d */ | cut -f1 -d/); do
                  echo "Building profile '$p'";
                  check_ecr.py --image_name $p --aws_region ${AWS::Region} --container_namespace ${CostTagValue}-container;
                  cd $p;
                  bash build.sh;
                  cd ..
                done

  PipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub codepipeline-${AWS::Region}-${CostTagValue}-container
      Tags:
        - Key: !Sub ${CostTagKey}
          Value: !Sub ${CostTagValue}

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      ArtifactStore: 
        Type: S3
        Location: !Ref PipelineBucket
      Name: !Sub ${CostTagValue}-Container-Pipeline
      RestartExecutionOnUpdate: False
      RoleArn: !GetAtt ContainerPipelineRole.Arn
      Tags: 
        - Key: !Sub ${CostTagKey}
          Value: !Sub ${CostTagValue}
      Stages:
        - Name: !Sub ${CostTagValue}-Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                BranchName: !Sub ${CodeCommitSourceBranch}
                OutputArtifactFormat: CODEBUILD_CLONE_REF
                PollForSourceChanges: "false"
                RepositoryName: !Sub ${CodeCommitSourceRepo}
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Sub ${AWS::Region}
              Namespace: SourceVariables

        - Name: !Sub ${CostTagValue}-Build-Profiles
          Actions:
            - Name: profiles
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref ProfileContainerCodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts: []
              Region: !Sub ${AWS::Region}
